services:
  db:
    build: ./db
    container_name: build-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=build

  api:
    build: ./api
    entrypoint: ./entrypoint.sh
    container_name: build-api
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./api:/home/node/api
    depends_on:
      - db

  app:
    build: ./app
    container_name: build-app
    ports:
      - "443:443"
    volumes:
      - ./app/policiacivil.crt:/etc/nginx/certs/policiacivil.crt:ro
      - ./app/policiacivil.key:/etc/nginx/certs/policiacivil.key:ro
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/dist:/usr/share/nginx/html:ro
    depends_on:
      - api
    command: nginx -g "daemon off;"